version: '3'
services:
  redisdb:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
  api:
    build:
      dockerfile: Dockerfile
      context: .
    image: easy-bazaar:1.0
    ports:
      - 8080:8080
    container_name: easy-bazaar
    depends_on:
      - redisdb
